### ISSUE TITLE
GLB model not displayed in Jetpack Compose

### ISSUE THREAD

**Issue by JohanAlbrectsen** [sceneview/sceneview#275]
I've written the following Kotlin code (Jetpack Compose), and it doesn't display any glb model. Not sure why. Any help is greatly appreciated!

```kotlin
val nodes = remember { mutableStateListOf<Node>() }

Scene(
    nodes = nodes,
    modifier = Modifier
        .fillMaxSize(),
    onCreate = { sceneView ->
        sceneView.modelLoader.loadModelAsync(
            fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
            onResult = { model ->
                model?.let { model ->
                    val node = ModelNode(
                        sceneView,
                        model
                    )
                    nodes.add(node)
                }
            }
        )
    },
)
```

**Comment by NohaSamir** [comment]
Try to `setLifecycle(lifecycle)`. Here is a full [example](https://github.com/NohaSamir/SceneView/blob/master/app/src/main/java/com/example/sceneview/MainActivity.kt)

**Comment by JohanAlbrectsen** [comment]
@NohaSamir Thank you so much! It brought me a step closer! I've added the line and it's not rendering the model.... kind of. Please take a look at this screen-recording, it looks completely wrong:
https://drive.google.com/file/d/14YXCS0m5Y7Y-D8vlZMgj2Tk7vs1wzonK/view?usp=sharing

1. The background is completely black, how can I set it to what I want?
2. How can I center the model and make it interactable (drag up and down)?

Here's the current code which is responsible for the video:

```kotlin
Box(modifier = Modifier
.fillMaxWidth()
.padding(top = 150.dp, bottom = 200.dp)
.fillMaxHeight()) {

    Scene(
        nodes = nodes,
        modifier = Modifier
            .fillMaxSize(),
        onCreate = { sceneView ->
            sceneView.apply {
                setLifecycle(lifecycle = lifecycle)
                sceneView.lifecycleScope.launch {
                    sceneView.modelLoader.loadModelAsync(
                        fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
                        onResult = { model ->
                            model?.let { model ->
                                val node = ModelNode(
                                    sceneView,
                                    model
                                )

                                nodes.add(node)
                            }
                        }
                    )
                }
            }
        },
    )
}
```

Thank you very much!
Kind regards, Johan

**Comment by NohaSamir** [comment]
- Add a background using sceneView.loadHdrSkybox
 - you can change the position of the ModelNode
 - I didn't try to make it draggable, By default you are able to drag the scenview not the model
 
 ```
 sceneView.lifecycleScope.launchWhenCreated {
                        val hdrFile = "environments/studio_small_09_2k.hdr"
                        sceneView.loadHdrIndirectLight(hdrFile, specularFilter = true) {
                            intensity(30_000f)
                        }
                        sceneView.loadHdrSkybox(hdrFile) {
                            intensity(50_000f)
                        }

                        sceneView.modelLoader.loadModelAsync(
                            fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
                            onResult = { model ->
                                model?.let {

                                    val modelNode = ModelNode(sceneView, model).apply {
                                        transform(
                                            position = Position(z = -6.0f),
                                            rotation = Rotation(x = 90.0f, z = 90f)
                                        )
                                    }
                                    sceneView.addChildNode(modelNode)
                                }
                            }
                        )
                    }
                   
```
![Screenshot_20230618_170959](https://github.com/SceneView/sceneview-android/assets/25500250/09bc0e77-6506-488c-8e4d-81e7da7c8305)

**Comment by JohanAlbrectsen** [comment]
Thank you very much, I've done those things and I'm almost at my goal. I little more help is greatly appreciated 🙏🏻.

From your screen-shot, the model looks to be centered perfectly and with a solid background color as background. If you look at my attachment, the model is not centered in the "room", let's call it, and I'm not particularly interested in a background graphic anyway. Just a solid color. And is it possible to always centre a model, no matter its size? So it's default is center?
Thank you very much,
Kind regards!

https://github.com/SceneView/sceneview-android/assets/109629518/99d13785-5677-4af3-aa08-5c4943acdd80

**Comment by JohanAlbrectsen** [comment]
@NohaSamir Thank you very much!
I tried the following code:

```kotlin
Box(modifier = Modifier
                .fillMaxWidth()
                .padding(top = 150.dp, bottom = 200.dp)
                .fillMaxHeight()) {

                Scene(
                    nodes = nodes,
                    modifier = Modifier
                        .fillMaxSize().background(Color.Red),
                    onCreate = { sceneView ->
                        sceneView.apply {

                            sceneView.uiHelper.isOpaque = false
                            sceneView.filamentView.blendMode = View.BlendMode.TRANSLUCENT

                            setLifecycle(lifecycle = lifecycle)
                            sceneView.lifecycleScope.launch {

                                sceneView.modelLoader.loadModelAsync(
                                    fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
                                    onResult = { model ->
                                        model?.let { model ->
                                            val node = ModelNode(
                                                sceneView,
                                                model
                                            ).apply {
                                                transform(
                                                    position = Position(z = -6.0f),
                                                    rotation = Rotation(x = 90.0f, z = 90f)
                                                )
                                            }

                                            nodes.add(node)
                                        }
                                    }
                                )
                            }
                        }
                    },
                )
            }
```

Unfortunately the scene is still completely black 😢.

**Comment by NohaSamir** [comment]
Instead of nodes.add(node), Try sceneView.addChildNode(node)

**Comment by gauravbiyani033** [comment]
I am not using jetpack compose based sceneview so I dont know whether it helps or not but this is how I did it:
- For centering the model, there is method implemented in sceneview itself. Try using this method on modelnode that you have created `modelNode.centerModel()`. This centered the model for me.

- As for background, I also faced a similar issue. For me creating a skybox fixed the issue. Try applying a skybox and you can pass in a color to skybox. I used the below implementation. But color needs to be passed in linear color format. Check the filament documentation on how to convert hexcode to linear color format.
`sceneview.skybox = Skybox.Builder().color(colors).build(Filament.engine)`

**Comment by JohanAlbrectsen** [comment]
@gauravbiyani033 Thank you so much! `sceneview.skybox = Skybox.Builder().color(colors).build(Filament.engine)` worked! I can't find `modelNode.centerModel()`, I've tried access the function on a `ModelNode` and a `Model`, but none of them seem to have the `centerModel()` available. If you could please show me how you called that it would be greatly appreciated. And it really warms my heart that multiple people are willing to answer my questions,
Kind regards!

**Comment by gauravbiyani033** [comment]
@JohanAlbrectsen, I think its odd there is no centerModel method, cause I am able to use it, if you can't find the centerModel method in modelNode, you can try implementing it yourself. Attaching the code below sceneview has used to implement center the model on the screen
```
    fun centerModel(origin: Position = Position(x = 0.0f, y = 0.0f, z = 0.0f)) {
        doOnModelLoaded { modelInstance ->
            val center =
                modelInstance.model.boundingBox.center.let { v -> Float3(v[0], v[1], v[2]) }
            val halfExtent =
                modelInstance.model.boundingBox.halfExtent.let { v -> Float3(v[0], v[1], v[2]) }
            modelPosition = -(center + halfExtent * origin) * modelScale
        }
    }
```
You can pass this centerModel your modelNode and I think this should work

**Comment by JohanAlbrectsen** [comment]
Hi! Thank you very much for the `function`. This is the result I'm getting, not exactly what I'm looking for:
https://github.com/SceneView/sceneview-android/assets/109629518/31136a55-9eae-48a1-9810-f7450c41082d

What version of scene view do you have, and do you also have the Augmented Reality part? Maybe that's where the `centerModel()` comes from?

Here's my code by the way:
```kotlin
Scene(
nodes = nodes,
modifier = Modifier
.fillMaxSize(),
onCreate = { sceneView ->
    sceneView.apply {
        sceneView.skybox = Skybox.Builder().color(750f / 255f, 750f / 255f, 750f / 255f, 1f).build(sceneView.engine)

        setLifecycle(lifecycle = lifecycle)
        sceneView.lifecycleScope.launch {

            sceneView.modelLoader.loadModelAsync(
                fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
                onResult = { model ->
                    model?.let { model ->
                        val node = ModelNode(
                            sceneView,
                            model
                        ).apply {
                            transform(
                                position = Position(z = -6.0f),
                                rotation = Rotation(x = 90.0f, z = 90f)
                            )
                        }

                        val modelScale = 1f
                        val center =
                            node.model.boundingBox.center.let { v -> Float3(v[0], v[1], v[2]) }
                        val halfExtent =
                            node.model.boundingBox.halfExtent.let { v -> Float3(v[0], v[1], v[2]) }
                        val modelPosition = -(center + halfExtent * Position(x = 0.0f, y = 0.0f, z = 0.0f)) * modelScale

                        node.position = modelPosition
                        nodes.add(node)
                    }
                }
            )
        }
    }
},
)
```

Kind regards

**Comment by gauravbiyani033** [comment]
Hey, Yeah my app does have an AR component, but that should not be the reason. I am using arsceneview 0.9.9 version. Reducing modelScale could help as I think the model is quite large to fit on the screen. So can you try decreasing modelScale and see what effect it has ?

**Comment by JohanAlbrectsen** [comment]
Yeah, I tried but setting it to 0.5, really didn't do much. I have a video of how I want the positioning of my model, take a look:

https://github.com/SceneView/sceneview-android/assets/109629518/96d77eb7-91a1-4679-b9d1-30163d194d01

I also tried downgrading to 0.9.9, didn't compile :(. 

This is the current result:


https://github.com/SceneView/sceneview-android/assets/109629518/832b538d-9010-4fbb-a984-f77bba8cab72

This is my code:

```kotlin
Box(modifier = Modifier
.fillMaxWidth()
.padding(top = 150.dp, bottom = 200.dp)
.fillMaxHeight()) {

    Scene(
        nodes = nodes,
        modifier = Modifier
            .fillMaxSize(),
        onCreate = { sceneView ->
            sceneView.apply {
                sceneView.skybox = Skybox.Builder().color(750f / 255f, 750f / 255f, 750f / 255f, 1f).build(sceneView.engine)

                setLifecycle(lifecycle = lifecycle)
                sceneView.lifecycleScope.launch {

                    sceneView.modelLoader.loadModelAsync(
                        fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
                        onResult = { model ->
                            model?.let { model ->
                                val node = ModelNode(
                                    sceneView,
                                    model
                                )

                                val modelScale = 0.5f
                                val center =
                                    node.model.boundingBox.center.let { v -> Float3(v[0], v[1], v[2]) }
                                val halfExtent =
                                    node.model.boundingBox.halfExtent.let { v -> Float3(v[0], v[1], v[2]) }
                                val modelPosition = -(center + halfExtent * Position(x = 0.0f, y = 0.0f, z = 0.0f)) * modelScale

                                node.position = modelPosition
                                nodes.add(node)
                            }
                        }
                    )
                }
            }
        },
    )
}
```

**Comment by gauravbiyani033** [comment]
Hey, do you have an option to set `node.modelPosition` ? If you have the option, try setting `node.modelPosition = modelPosition` instead of `node.position = modelPosition`

**Comment by JohanAlbrectsen** [comment]
No, unfortunately not, these are the options I have:

<img width="1043" alt="Screenshot 2023-06-26 at 11 46 10" src="https://github.com/SceneView/sceneview-android/assets/109629518/0c6b725c-d994-4a9d-accb-69c0a8ed2f8f">

Tried `.centerPosition = modelPosition`, didn't work :(

**Comment by gauravbiyani033** [comment]
Hey try `centerPosition = Position(0.0f, 0.0f, 0.0f)`. If you see the function I sent, sceneview asks for an origin. centerPosition could probably be it

**Comment by JohanAlbrectsen** [comment]
Doesn't seem to work, if this implementation is what you mean:

```kotlin
Scene(
nodes = nodes,
modifier = Modifier
.fillMaxSize(),
onCreate = { sceneView ->
    sceneView.apply {
        sceneView.skybox = Skybox.Builder().color(750f / 255f, 750f / 255f, 750f / 255f, 1f).build(sceneView.engine)

        setLifecycle(lifecycle = lifecycle)
        sceneView.lifecycleScope.launch {

            sceneView.modelLoader.loadModelAsync(
                fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
                onResult = { model ->
                    model?.let { model ->
                        val node = ModelNode(
                            sceneView,
                            model
                        )

                        /*val modelScale = 0.5f
                        val center =
                            node.model.boundingBox.center.let { v -> Float3(v[0], v[1], v[2]) }
                        val halfExtent =
                            node.model.boundingBox.halfExtent.let { v -> Float3(v[0], v[1], v[2]) }
                        val modelPosition = -(center + halfExtent * Position(x = 0.0f, y = 0.0f, z = 0.0f)) * modelScale
                        */
                        node.centerPosition = Position(0.0f, 0.0f, 0.0f)
                        nodes.add(node)
                    }
                }
            )
        }
    }
},
)
```

**Comment by JohanAlbrectsen** [comment]
Thanks, where are you getting this `onFrame`? It's not available on `SceneView` for me.

**Comment by JohanAlbrectsen** [comment]
If someone has a solution to this and is willing to spend a couple hours on a call with me, I'll pay that guy/gal $100 and we'll post the solution here. 
Please contact me at: johanalbrectsen@gmail.com

**Comment by ThomasGorisse** [comment]
https://github.com/SceneView/sceneview-android/blob/main/samples/model-viewer/src/main/java/io/github/sceneview/sample/modelviewer/MainFragment.kt#L30-L50

**Comment by threedalpeng** [comment]
How about replacing `nodes = nodes` to `nodes = nodes.toList()`?

I found that comparing `sceneViewNodes` and `nodes` inside `Scene` composable does not work as expected when passing `nodes` (with `= remember { mutableStateListOf()`) directly and then using `nodes.add()` for new node, because those are already the same.

Might need to change Compose usage of README, or add some comments

**Comment by Takexito** [comment]
I just ran into a similar issue with `ARScene` `Composable`. Under the hood, it assigns a list of `nodes` from the `ARScene` parameters to an internal `var sceneViewNodes`. And `sceneView.addChild(it)` inside the `update` lambda for `AndroidView` will never be called because `nodes` and `sceneViewNodes` are the same list.

I fixed it by replacing `nodes = nodes` with `nodes = nodes.toList()`, same as @threedalpeng

**Comment by JohanAlbrectsen** [comment]
I've tried the following:

`nodes = nodes.toList()`. The model is still not centered :(

```kotlin
Box(modifier = Modifier
.fillMaxWidth()
.padding(top = 150.dp, bottom = 200.dp)
.fillMaxHeight()) {

    Scene(
        nodes = nodes.toList(),
        modifier = Modifier
            .fillMaxSize(),
        onCreate = { sceneView ->
            sceneView.apply {
                sceneView.skybox = Skybox.Builder().color(750f / 255f, 750f / 255f, 750f / 255f, 1f).build(sceneView.engine)

                setLifecycle(lifecycle = lifecycle)
                sceneView.lifecycleScope.launch {

                    sceneView.modelLoader.loadModelAsync(
                        fileLocation = "https://test-aorist-bucket.s3.amazonaws.com/models/artwork/187.1.glb",
                        onResult = { model ->
                            model?.let { model ->
                                val node = ModelNode(
                                    sceneView,
                                    model
                                )
                                node.centerModel()

                                nodes.add(node)
                            }
                        }
                    )
                }
            }
        },
    )
}
```

**Comment by dinakar-m** [comment]
removed deprecated  - launchWhenCreated
> launchWhenCreated deprecated. 'launchWhenCreated(suspend CoroutineScope.() -> Unit): Job' is deprecated. launchWhenCreated is deprecated as it can lead to wasted resources in some cases. Replace with suspending repeatOnLifecycle to run the block whenever the Lifecycle state is at least Lifecycle.State.CREATED.
 

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.repeatOnLifecycle
import com.gorisse.thomas.lifecycle.lifecycle
import com.gorisse.thomas.lifecycle.lifecycleScope
import io.github.sceneview.Scene
import io.github.sceneview.loaders.loadHdrIndirectLight
import io.github.sceneview.loaders.loadHdrSkybox
import io.github.sceneview.math.Position
import io.github.sceneview.math.Rotation
import io.github.sceneview.nodes.ModelNode
import io.github.sceneview.nodes.Node
import kotlinx.coroutines.launch

private const val TAG = "SceneExampleView"
@Composable
fun SceneExampleView() {
    val nodes = remember { mutableStateListOf<Node>() }

    Box(modifier = Modifier.fillMaxSize()) {
        Scene(
            modifier = Modifier.fillMaxSize(),
            nodes = nodes,
            onCreate = { sceneView ->
                sceneView.apply {
                    setLifecycle(lifecycle)

                    // Apply your configuration
                    sceneView.lifecycleScope.launch {
                        sceneView.lifecycle.repeatOnLifecycle(Lifecycle.State.CREATED) {
                            val hdrFile = "models/spiderbot.glb"
                            loadHdrIndirectLight(hdrFile, specularFilter = true) {
                                intensity(30_000f)
                            }
                            loadHdrSkybox(hdrFile) {
                                intensity(50_000f)
                            }

                            val model = modelLoader.loadModel("models/MaterialSuite.glb")!!
                            val modelNode = ModelNode(sceneView, model).apply {
                                transform(
                                    position = Position(z = -4.0f),
                                    rotation = Rotation(x = 15.0f)
                                )
                                scaleToUnitsCube(2.0f)
                            }
                            addChildNode(modelNode)
                        }
                    }
                }
            }
        )
    }
}


![image](https://github.com/SceneView/sceneview-android/assets/102947879/c819db63-c11f-4a73-8717-e56e275fd084)

**Comment by dinkar1708** [comment]
removed deprecated  - launchWhenCreated
> launchWhenCreated deprecated. 'launchWhenCreated(suspend CoroutineScope.() -> Unit): Job' is deprecated. launchWhenCreated is deprecated as it can lead to wasted resources in some cases. Replace with suspending repeatOnLifecycle to run the block whenever the Lifecycle state is at least Lifecycle.State.CREATED.
 

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.repeatOnLifecycle
import com.gorisse.thomas.lifecycle.lifecycle
import com.gorisse.thomas.lifecycle.lifecycleScope
import io.github.sceneview.Scene
import io.github.sceneview.loaders.loadHdrIndirectLight
import io.github.sceneview.loaders.loadHdrSkybox
import io.github.sceneview.math.Position
import io.github.sceneview.math.Rotation
import io.github.sceneview.nodes.ModelNode
import io.github.sceneview.nodes.Node
import kotlinx.coroutines.launch

private const val TAG = "SceneExampleView"
@Composable
fun SceneExampleView() {
    val nodes = remember { mutableStateListOf<Node>() }

    Box(modifier = Modifier.fillMaxSize()) {
        Scene(
            modifier = Modifier.fillMaxSize(),
            nodes = nodes,
            onCreate = { sceneView ->
                sceneView.apply {
                    setLifecycle(lifecycle)

                    // Apply your configuration
                    sceneView.lifecycleScope.launch {
                        sceneView.lifecycle.repeatOnLifecycle(Lifecycle.State.CREATED) {
                            val hdrFile = "models/spiderbot.glb"
                            loadHdrIndirectLight(hdrFile, specularFilter = true) {
                                intensity(30_000f)
                            }
                            loadHdrSkybox(hdrFile) {
                                intensity(50_000f)
                            }

                            val model = modelLoader.loadModel("models/MaterialSuite.glb")!!
                            val modelNode = ModelNode(sceneView, model).apply {
                                transform(
                                    position = Position(z = -4.0f),
                                    rotation = Rotation(x = 15.0f)
                                )
                                scaleToUnitsCube(2.0f)
                            }
                            addChildNode(modelNode)
                        }
                    }
                }
            }
        )
    }
}


![image](https://github.com/SceneView/sceneview-android/assets/14831652/6f112ad3-d1dd-454a-bf2b-122c73d83f9d)

**Comment by JohanAlbrectsen** [comment]
> https://github.com/SceneView/sceneview-android/blob/main/samples/model-viewer/src/main/java/io/github/sceneview/sample/modelviewer/MainFragment.kt#L30-L50
> 
> ```kotlin
>              val hdrFile = "environments/studio_small_09_2k.hdr" 
>              sceneView.loadHdrIndirectLight(hdrFile, specularFilter = true) { 
>                  intensity(30_000f) 
>              } 
>              sceneView.loadHdrSkybox(hdrFile) { 
>                  intensity(50_000f) 
>              } 
>   
>              val model = sceneView.modelLoader.loadModel("models/MaterialSuite.glb")!! 
>              val modelNode = ModelNode(sceneView, model).apply { 
>                  transform( 
>                      position = Position(z = -4.0f), 
>                      rotation = Rotation(x = 15.0f) 
>                  ) 
>                  scaleToUnitsCube(2.0f) 
>                  playAnimation() 
>              } 
>              sceneView.addChildNode(modelNode)
> ```

This worked for me! Can I ask you, did you use my specific model in this case (for position and rotation), or is it applicable for all types of models, no matter size, shape and initial position?

**Comment by ThomasGorisse** [comment]
Hi,
To center your model (whatever the position it had at the glTF export time) use `centerOrigin()` after `scaleToUnitsCube()`
```kotlin
    scaleToUnitsCube(2.0f)
    centerOrigin()
    playAnimation()
```

**Comment by JohanAlbrectsen** [comment]
@ThomasGorisse Thanks 🙏🏻. `centerOrigin()` is not available for `ModelNode`. I'm using version `1.0.8` since that's what's compatible with my project, but when I updated to the latest (`1.0.12`), autocomplete didn't seem to suggest `centerOrigin()` is a method that's available.

**Comment by ravirajdarisi** [comment]
> Try to `setLifecycle(lifecycle)`. Here is a full [example](https://github.com/NohaSamir/SceneView/blob/master/app/src/main/java/com/example/sceneview/MainActivity.kt)

Thanks for the code example, it really helps !!!

**Comment by ravirajdarisi** [comment]
@JohanAlbrectsen I am having a similar problem, If you are able to get it right, could you share the codebase, that would be a great help !!!

**Comment by JohanAlbrectsen** [comment]
This has been resolved due to the help of @ThomasGorisse ,
Thank you so much! Would be completely lost if it wasn't for you 😊, and thanks to all the others for their great input!
Kind regards.

**Comment by tomriddle25** [comment]
@threedalpeng @Takexito I am facing a similar problem with nodes in using Scene in Jetpack compose. 
My list of nodes depend upon another mutableState, and no matter what, I am not able to get the changed list of nodes to reflect. 
Would really appreciate any help. 

Cann post code if needed.
